spring.security.oauth2.client.registration.google.client-secret=TU_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.data.mongodb.uri=${MONGO_URL}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.data.redis.url=${REDIS_URL}

spring.session.store-type=redis
spring.session.timeout=1800
#server.tomcat.max-threads=2000
#server.tomcat.accept-count=2000
#server.tomcat.max-connections=20000

# MercadoPago Configuration - Usar variables de entorno
mercadopago.access.token=${MP_ACCESS_TOKEN:}
mercadopago.public.key=${MP_PUBLIC_KEY:}
app.payment.success.url=https://${RAILWAY_PUBLIC_DOMAIN}/Api/Payment/success
app.payment.failure.url=https://${RAILWAY_PUBLIC_DOMAIN}/Api/Payment/failure
app.payment.pending.url=https://${RAILWAY_PUBLIC_DOMAIN}/Api/Payment/pending
