package com.ProyectoAula.GymAssist.mongoModels;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.bson.codecs.pojo.annotations.BsonProperty;
import org.bson.types.ObjectId;
import org.springframework.data.mongodb.core.mapping.Document;
import org.openapitools.*;
import java.time.OffsetDateTime;
import jakarta.validation.constraints.NotNull;


import java.util.*;
import jakarta.annotation.Generated;

/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: admin
 * Language: Java
 * Template: Spring Data
 * Generated on 2025-04-25
 */
@JsonTypeName("admin")
@Generated(value = "com.mongodb.migrator.application.codegen.config.java.JavaSpringCodegenConfig", date = "2025-04-25T23:08:41.064542100-05:00[America/Bogota]", comments = "Generator version: 7.10.0")@Document("admin")
public class AdminEntity {

  @BsonProperty("_id")
  private ObjectId mongoId = null;

  @BsonProperty("id")
  private Long id;

  public AdminEntity mongoId(ObjectId mongoId) {
    this.mongoId = mongoId;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  
  @JsonProperty("_id")
  public ObjectId getMongoId() {
    return mongoId;
  }

  public void setMongoId(ObjectId mongoId) {
    this.mongoId = mongoId;
  }

  public AdminEntity id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  
  @JsonProperty("id")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminEntity admin = (AdminEntity) o;
    return Objects.equals(this.mongoId, admin.mongoId) &&
        Objects.equals(this.id, admin.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mongoId, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminEntity {\n");
    sb.append("    mongoId: ").append(toIndentedString(mongoId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
