package com.ProyectoAula.GymAssist.mongoModels;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.bson.codecs.pojo.annotations.BsonProperty;
import org.bson.types.ObjectId;
import org.springframework.data.mongodb.core.mapping.Document;
import org.openapitools.*;
import java.time.OffsetDateTime;
import jakarta.validation.constraints.NotNull;


import java.util.*;
import jakarta.annotation.Generated;

/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: client
 * Language: Java
 * Template: Spring Data
 * Generated on 2025-04-25
 */
@JsonTypeName("client")
@Generated(value = "com.mongodb.migrator.application.codegen.config.java.JavaSpringCodegenConfig", date = "2025-04-25T23:05:17.426110800-05:00[America/Bogota]", comments = "Generator version: 7.10.0")@Document("client")
public class ClientEntity {

  @BsonProperty("_id")
  private ObjectId mongoId = null;

  @BsonProperty("correo")
  private String correo;

  @BsonProperty("idDocumento")
  private String idDocumento;

  @BsonProperty("mensualidad")
  private String mensualidad;

  @BsonProperty("nombre")
  private String nombre;

  @BsonProperty("telefono")
  private Integer telefono;

  @BsonProperty("id")
  private Long id;

  @BsonProperty("adminId")
  private Long adminId;

  @BsonProperty("gymId")
  private Long gymId;

  public ClientEntity mongoId(ObjectId mongoId) {
    this.mongoId = mongoId;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  
  @JsonProperty("_id")
  public ObjectId getMongoId() {
    return mongoId;
  }

  public void setMongoId(ObjectId mongoId) {
    this.mongoId = mongoId;
  }

  public ClientEntity correo(String correo) {
    this.correo = correo;
    return this;
  }

  /**
   * Get correo
   * @return correo
   */
  
  @JsonProperty("correo")
  public String getCorreo() {
    return correo;
  }

  public void setCorreo(String correo) {
    this.correo = correo;
  }

  public ClientEntity idDocumento(String idDocumento) {
    this.idDocumento = idDocumento;
    return this;
  }

  /**
   * Get idDocumento
   * @return idDocumento
   */
  
  @JsonProperty("idDocumento")
  public String getIdDocumento() {
    return idDocumento;
  }

  public void setIdDocumento(String idDocumento) {
    this.idDocumento = idDocumento;
  }

  public ClientEntity mensualidad(String mensualidad) {
    this.mensualidad = mensualidad;
    return this;
  }

  /**
   * Get mensualidad
   * @return mensualidad
   */
  
  @JsonProperty("mensualidad")
  public String getMensualidad() {
    return mensualidad;
  }

  public void setMensualidad(String mensualidad) {
    this.mensualidad = mensualidad;
  }

  public ClientEntity nombre(String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * Get nombre
   * @return nombre
   */
  
  @JsonProperty("nombre")
  public String getNombre() {
    return nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public ClientEntity telefono(Integer telefono) {
    this.telefono = telefono;
    return this;
  }

  /**
   * Get telefono
   * @return telefono
   */
  
  @JsonProperty("telefono")
  public Integer getTelefono() {
    return telefono;
  }

  public void setTelefono(Integer telefono) {
    this.telefono = telefono;
  }

  public ClientEntity id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  
  @JsonProperty("id")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ClientEntity adminId(Long adminId) {
    this.adminId = adminId;
    return this;
  }

  /**
   * Get adminId
   * @return adminId
   */
  
  @JsonProperty("adminId")
  public Long getAdminId() {
    return adminId;
  }

  public void setAdminId(Long adminId) {
    this.adminId = adminId;
  }

  public ClientEntity gymId(Long gymId) {
    this.gymId = gymId;
    return this;
  }

  /**
   * Get gymId
   * @return gymId
   */
  
  @JsonProperty("gymId")
  public Long getGymId() {
    return gymId;
  }

  public void setGymId(Long gymId) {
    this.gymId = gymId;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientEntity client = (ClientEntity) o;
    return Objects.equals(this.mongoId, client.mongoId) &&
        Objects.equals(this.correo, client.correo) &&
        Objects.equals(this.idDocumento, client.idDocumento) &&
        Objects.equals(this.mensualidad, client.mensualidad) &&
        Objects.equals(this.nombre, client.nombre) &&
        Objects.equals(this.telefono, client.telefono) &&
        Objects.equals(this.id, client.id) &&
        Objects.equals(this.adminId, client.adminId) &&
        Objects.equals(this.gymId, client.gymId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mongoId, correo, idDocumento, mensualidad, nombre, telefono, id, adminId, gymId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientEntity {\n");
    sb.append("    mongoId: ").append(toIndentedString(mongoId)).append("\n");
    sb.append("    correo: ").append(toIndentedString(correo)).append("\n");
    sb.append("    idDocumento: ").append(toIndentedString(idDocumento)).append("\n");
    sb.append("    mensualidad: ").append(toIndentedString(mensualidad)).append("\n");
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    telefono: ").append(toIndentedString(telefono)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    adminId: ").append(toIndentedString(adminId)).append("\n");
    sb.append("    gymId: ").append(toIndentedString(gymId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
