package com.ProyectoAula.GymAssist.mongoModels;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Arrays;
import org.bson.codecs.pojo.annotations.BsonProperty;
import org.bson.types.ObjectId;
import org.springframework.data.mongodb.core.mapping.Document;
import org.openapitools.*;
import java.time.OffsetDateTime;
import jakarta.validation.constraints.NotNull;


import java.util.*;
import jakarta.annotation.Generated;
import jakarta.persistence.Id;

/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: rutina
 * Language: Java
 * Template: Spring Data
 * Generated on 2025-04-23
 */
@JsonTypeName("rutina")
@Generated(value = "com.mongodb.migrator.application.codegen.config.java.JavaSpringCodegenConfig", date = "2025-04-23T20:31:20.848102300-05:00[America/Bogota]", comments = "Generator version: 7.10.0")@Document("rutina")
public class RutinaEntity {

  @BsonProperty("_id")
  private ObjectId mongoId = null;

  @Id
  @BsonProperty("id")
  private Long id;

  @BsonProperty("fotos")
  private byte[] fotos;

  @BsonProperty("grupoMuscular")
  private String grupoMuscular;

  @BsonProperty("repeticiones")
  private String repeticiones;

  @BsonProperty("series")
  private String series;

  @BsonProperty("gymId")
  private Long gymId;

  public RutinaEntity mongoId(ObjectId mongoId) {
    this.mongoId = mongoId;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  
  @JsonProperty("_id")
  public ObjectId getMongoId() {
    return mongoId;
  }

  public void setMongoId(ObjectId mongoId) {
    this.mongoId = mongoId;
  }

  public RutinaEntity id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  
  @JsonProperty("id")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public RutinaEntity fotos(byte[] fotos) {
    this.fotos = fotos;
    return this;
  }

  /**
   * Get fotos
   * @return fotos
   */
  
  @JsonProperty("fotos")
  public byte[] getFotos() {
    return fotos;
  }

  public void setFotos(byte[] fotos) {
    this.fotos = fotos;
  }

  public RutinaEntity grupoMuscular(String grupoMuscular) {
    this.grupoMuscular = grupoMuscular;
    return this;
  }

  /**
   * Get grupoMuscular
   * @return grupoMuscular
   */
  
  @JsonProperty("grupoMuscular")
  public String getGrupoMuscular() {
    return grupoMuscular;
  }

  public void setGrupoMuscular(String grupoMuscular) {
    this.grupoMuscular = grupoMuscular;
  }

  public RutinaEntity repeticiones(String repeticiones) {
    this.repeticiones = repeticiones;
    return this;
  }

  /**
   * Get repeticiones
   * @return repeticiones
   */
  
  @JsonProperty("repeticiones")
  public String getRepeticiones() {
    return repeticiones;
  }

  public void setRepeticiones(String repeticiones) {
    this.repeticiones = repeticiones;
  }

  public RutinaEntity series(String series) {
    this.series = series;
    return this;
  }

  /**
   * Get series
   * @return series
   */
  
  @JsonProperty("series")
  public String getSeries() {
    return series;
  }

  public void setSeries(String series) {
    this.series = series;
  }

  public RutinaEntity gymId(Long gymId) {
    this.gymId = gymId;
    return this;
  }

  /**
   * Get gymId
   * @return gymId
   */
  
  @JsonProperty("gymId")
  public Long getGymId() {
    return gymId;
  }

  public void setGymId(Long gymId) {
    this.gymId = gymId;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RutinaEntity rutina = (RutinaEntity) o;
    return Objects.equals(this.mongoId, rutina.mongoId) &&
        Objects.equals(this.id, rutina.id) &&
        Arrays.equals(this.fotos, rutina.fotos) &&
        Objects.equals(this.grupoMuscular, rutina.grupoMuscular) &&
        Objects.equals(this.repeticiones, rutina.repeticiones) &&
        Objects.equals(this.series, rutina.series) &&
        Objects.equals(this.gymId, rutina.gymId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mongoId, id, Arrays.hashCode(fotos), grupoMuscular, repeticiones, series, gymId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RutinaEntity {\n");
    sb.append("    mongoId: ").append(toIndentedString(mongoId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    fotos: ").append(toIndentedString(fotos)).append("\n");
    sb.append("    grupoMuscular: ").append(toIndentedString(grupoMuscular)).append("\n");
    sb.append("    repeticiones: ").append(toIndentedString(repeticiones)).append("\n");
    sb.append("    series: ").append(toIndentedString(series)).append("\n");
    sb.append("    gymId: ").append(toIndentedString(gymId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}