package com.ProyectoAula.GymAssist.mongoModels;

import java.net.URI;
import java.util.Objects;
import com.ProyectoAula.GymAssist.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.bson.codecs.pojo.annotations.BsonProperty;
import org.bson.types.ObjectId;
import org.springframework.data.mongodb.core.mapping.Document;
import org.openapitools.*;
import java.time.OffsetDateTime;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.Valid;


import java.util.*;
import jakarta.annotation.Generated;
import jakarta.persistence.Id;

/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: user
 * Language: Java
 * Template: Spring Data
 * Generated on 2025-04-23
 */
@JsonTypeName("user")
@Generated(value = "com.mongodb.migrator.application.codegen.config.java.JavaSpringCodegenConfig", date = "2025-04-23T20:32:34.385757600-05:00[America/Bogota]", comments = "Generator version: 7.10.0")@Document("user")
public class UserEntity {

  @BsonProperty("_id")
  private ObjectId mongoId = null;

  @Id
  @BsonProperty("id")
  private Long id;

  @BsonProperty("email")
  private String email;

  @BsonProperty("password")
  private String password;

  @BsonProperty("role")
  private String role;

  @BsonProperty("username")
  private String username;

  @BsonProperty("userRoles")
  
  private List<@Valid UserUserRolesInnerEntity> userRoles = new ArrayList<>();

  public UserEntity mongoId(ObjectId mongoId) {
    this.mongoId = mongoId;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  
  @JsonProperty("_id")
  public ObjectId getMongoId() {
    return mongoId;
  }

  public void setMongoId(ObjectId mongoId) {
    this.mongoId = mongoId;
  }

  public UserEntity id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  
  @JsonProperty("id")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public UserEntity email(String email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  
  @JsonProperty("email")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserEntity password(String password) {
    this.password = password;
    return this;
  }

  /**
   * Get password
   * @return password
   */
  
  @JsonProperty("password")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public UserEntity role(String role) {
    this.role = role;
    return this;
  }

  /**
   * Get role
   * @return role
   */
  
  @JsonProperty("role")
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public UserEntity username(String username) {
    this.username = username;
    return this;
  }

  /**
   * Get username
   * @return username
   */
  
  @JsonProperty("username")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public UserEntity userRoles(List<@Valid UserUserRolesInnerEntity> userRoles) {
    this.userRoles = userRoles;
    return this;
  }

  public UserEntity addUserRolesItem(UserUserRolesInnerEntity userRolesItem) {
    if (this.userRoles == null) {
      this.userRoles = new ArrayList<>();
    }
    this.userRoles.add(userRolesItem);
    return this;
  }

  /**
   * Get userRoles
   * @return userRoles
   */
  
  @JsonProperty("userRoles")
  public List<@Valid UserUserRolesInnerEntity> getUserRoles() {
    return userRoles;
  }

  public void setUserRoles(List<@Valid UserUserRolesInnerEntity> userRoles) {
    this.userRoles = userRoles;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserEntity user = (UserEntity) o;
    return Objects.equals(this.mongoId, user.mongoId) &&
        Objects.equals(this.id, user.id) &&
        Objects.equals(this.email, user.email) &&
        Objects.equals(this.password, user.password) &&
        Objects.equals(this.role, user.role) &&
        Objects.equals(this.username, user.username) &&
        Objects.equals(this.userRoles, user.userRoles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mongoId, id, email, password, role, username, userRoles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserEntity {\n");
    sb.append("    mongoId: ").append(toIndentedString(mongoId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    userRoles: ").append(toIndentedString(userRoles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}