package com.ProyectoAula.GymAssist.mongoRepository;

import org.springframework.data.mongodb.repository.MongoRepository;
import com.ProyectoAula.GymAssist.mongoModels.RutinaEntity;

import java.util.List;

import org.bson.types.ObjectId;

/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: rutina
 * Language: Java
 * Template: Spring Data
 * Generated on 2025-04-23
 */
public interface RutinaRepository extends MongoRepository<RutinaEntity, ObjectId> {
    List<RutinaEntity> findByGymId(ObjectId gymId);
    List<RutinaEntity> findByGrupoMuscular(String grupoMuscular);
    List<RutinaEntity> findByGrupoMuscularIgnoreCaseAndGymId(String grupoMuscular, ObjectId gymId);
}
