package com.ProyectoAula.GymAssist.mongoRepository;


import org.springframework.data.mongodb.repository.MongoRepository;
import com.ProyectoAula.GymAssist.mongoModels.GimnasiosEntity;
import java.util.Optional;
import org.bson.types.ObjectId;


/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: client
 * Language: Java
 * Template: Spring Data
 * Generated on 2025-04-25
 */
public interface GimnasiosRepository extends MongoRepository<GimnasiosEntity, ObjectId> {
    Optional<GimnasiosEntity> findByAdminId(Long adminId);
    void deleteByAdminId(Long adminId);
}