package com.ProyectoAula.GymAssist.mongoRepository;

import org.springframework.data.mongodb.repository.MongoRepository;

import com.ProyectoAula.GymAssist.mongoModels.GimnasiosEntity;

/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: gimnasios
 * Language: Java
 * Template: Spring Data
 * Generated on 2025-04-23
 */
public interface GimnasiosRepository extends MongoRepository<GimnasiosEntity, Long> {
}
