package com.ProyectoAula.GymAssist.mongoRepository;

import org.bson.types.ObjectId;
import org.springframework.data.mongodb.repository.MongoRepository;

import com.ProyectoAula.GymAssist.mongoModels.MedicionesEntity;

/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: mediciones
 * Language: Java
 * Template: Spring Data
 * Generated on 2025-04-25
 */
public interface MedicionesRepository extends MongoRepository<MedicionesEntity, ObjectId> {
}