package com.ProyectoAula.GymAssist.mongoRepository;

import org.springframework.data.mongodb.repository.MongoRepository;

import com.ProyectoAula.GymAssist.mongoModels.PlanEntity;

import java.util.List;

import org.bson.types.ObjectId;

/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: plan
 * Language: Java
 * Template: Spring Data
 * Generated on 2025-04-23
 */
public interface PlanRepository extends MongoRepository<PlanEntity, ObjectId> {
    // Custom query methods can be defined here if needed
    // For example, to find by clienteId:
    List<PlanEntity> findByClienteId(Long clienteId);
    List<PlanEntity> findByGymId(ObjectId gymId);
}