package com.ProyectoAula.GymAssist.mongoRepository;

import org.springframework.data.mongodb.repository.MongoRepository;
import com.ProyectoAula.GymAssist.mongoModels.UserEntity;

/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: user
 * Language: Java
 * Template: Spring Data
 * Generated on 2025-04-23
 */
public interface UserRepository extends MongoRepository<UserEntity, Long> {
}
